version: '3.8'

services:
  api:
    build: .
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    volumes:
      - .:/app:delegated
    restart: always

  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
